# Base configs
baseurl: "https://venturedude.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Archit Patel"
subtitle: "See the world through my eyes!"
author: "Archit Patel"
header:
 title: "Photography"
 subtitle: "by Archit Patel"
footer:
 name: "Hey there, my name is Archit"
 bio: "Coming Soon"
 github: "Follow me on Instagram <a href=\"https://https://www.instagram.com/archit16\">@TheAdventureDude</a>"
web_design: "AP"
social_urls:
  facebook: "https://www.facebook.com/archit16"
  twitter: "https://www.twitter.com/16archit"
  instagram: "https://www.instagram.com/theadventuredude"
  linkedin: "https://linkedin.com/in/architp"