# Base configs
baseurl: "https://architp16.github.io/VentureDude/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-JDHGHGK73N"

# UI configs
title: "Man Behind The Camera"
subtitle: "The Man Behind The Camera"
author: "Archit Patel 2020"
header:
 title: "Photography"
 subtitle: "by Archit Patel"
footer:
 name: "Hey there, my name is Archit"
 bio: "My mission is to create images that inspire current and future generations to respect and conserve the natural world and beyond."
 github: "Follow me on Instagram <a href=\"https://www.instagram.com/theadventuredude\">@TheAdventureDude</a>"
social_urls:
  facebook: "https://www.facebook.com/archit16"
  twitter: "https://www.twitter.com/16archit"
  instagram: "https://www.instagram.com/archit16"
  linkedin: "https://linkedin.com/in/architp"